name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore nuget packages
        run: nuget restore .\src\JiuLing.AutoUpgrade.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build core app
        run: msbuild .\src\JiuLing.AutoUpgrade\JiuLing.AutoUpgrade.csproj

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore .\src\JiuLing.AutoUpgrade.sln

      - name: Build shell app for netstandard2.0
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore --framework netstandard2.0

      - name: Build shell app for net5.0
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore --framework net5.0

      - name: Build shell app for net6.0
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore --framework net6.0

      - name: Build shell app for net7.0
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore --framework net7.0

      - name: Build shell app for net8.0
        run: dotnet build .\src\JiuLing.AutoUpgrade.Shell\JiuLing.AutoUpgrade.Shell.csproj --no-restore --framework net8.0

      - name: Build test app
        run: dotnet build .\src\JiuLing.AutoUpgrade.Test\JiuLing.AutoUpgrade.Test.csproj --no-restore
